version: "3.9"
services:
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    environment:
      RACK_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/app_development

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
